{
 "title": "Vault Usage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "AppRoles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Min AppRole Validity Period Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(vault_approle_rotation_validity_period_percent_total)"
    }
   ]
  },
  {
   "title": "Next Expiration Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(vault_approle_rotation_expiration_time_timestamp_seconds) - time()"
    }
   ]
  },
  {
   "title": "Median AppRole Validity Period Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, vault_approle_rotation_validity_period_percent_total)"
    }
   ]
  },
  {
   "title": "Median AppRole Validity Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, vault_approle_rotation_expiration_time_timestamp_seconds - vault_approle_rotation_creation_time_timestamp_seconds)"
    }
   ]
  },
  {
   "title": "Max AppRole Validity Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_approle_rotation_expiration_time_timestamp_seconds - vault_approle_rotation_creation_time_timestamp_seconds)"
    }
   ]
  },
  { "title": "Ssh Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Invokation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ssh_key_signer_success_bool == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Min SSH Cert Validity Period Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(ssh_key_signer_cert_lifetime_percent > 0)"
    }
   ]
  },
  {
   "title": "Next SSH Cert Expiration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(ssh_key_signer_cert_expiry_seconds) - time()"
    }
   ]
  },
  {
   "title": "Median SSH Cert Validity Period Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, ssh_key_signer_cert_lifetime_percent > 0)"
    }
   ]
  },
  {
   "title": "Max SSH Cert Validity Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ssh_key_signer_cert_lifetime_seconds_total)"
    }
   ]
  },
  {
   "title": "Median SSH Cert Validity Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, ssh_key_signer_cert_lifetime_seconds_total)"
    }
   ]
  },
  { "title": "AppRoles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "AppRole Expiry Period",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(vault_approle_rotation_validity_period_percent_total)",
     "legendFormat": "{{ role_name }}"
    }
   ]
  },
  {
   "title": "AppRole Expiry Period",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vault_approle_rotation_expiration_time_timestamp_seconds - vault_approle_rotation_creation_time_timestamp_seconds",
     "legendFormat": "{{ role_name }}"
    }
   ]
  },
  {
   "title": "AppRole Rotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count(vault_approle_rotation_rotated_secret_id_bool > 0) or vector(0)"
    }
   ]
  },
  { "title": "SSH Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cert Lifetime",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(ssh_key_signer_cert_lifetime_percent)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Invokation",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(time() - ssh_key_signer_run_timestamp_seconds)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}