{
 "title": "libvirt",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(libvirt_up, instance)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(libvirt_domain_interface_stats_receive_bytes_total{instance=~\"$instance\"}, domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Libvirt",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "libvirt_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(libvirt_domain_info_memory_usage_bytes{instance=~\"$instance\",domain=~\"$domain\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(libvirt_domain_info_cpu_time_seconds_total{instance=~\"$instance\",domain=~\"$domain\"}[$__rate_interval]) / libvirt_domain_info_virtual_cpus{instance=~\"$instance\",domain=~\"$domain\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Packet Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(libvirt_domain_interface_stats_receive_drops_total{instance=~\"$instance\",domain=~\"$domain\"}[$__rate_interval])",
     "legendFormat": "{{ domain }}"
    },
    {
     "expr": "-increase(libvirt_domain_interface_stats_transmit_drops_total{instance=~\"$instance\",domain=~\"$domain\"}[$__rate_interval])",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(libvirt_domain_interface_stats_receive_bytes_total{instance=~\"$instance\",domain=~\"$domain\"}[$__rate_interval])",
     "legendFormat": "{{ domain }}"
    },
    {
     "expr": "-increase(libvirt_domain_interface_stats_transmit_bytes_total{instance=~\"$instance\",domain=~\"$domain\"}[$__rate_interval])",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "libvirt_domains_number{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}