{
 "title": "Wireguard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(wireguard_bytes_received_total, instance)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "label_values(wireguard_bytes_received_total, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tunnelguard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Invokation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_tunnelguard_invocation_timestamp_seconds",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Last Handshake",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(time() - wireguard_tunnelguard_peer_handshake_timestamp_seconds)",
     "legendFormat": "{{ location }} {{ pubkey }}"
    }
   ]
  },
  {
   "title": "Tunnel Resets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wireguard_tunnelguard_peer_reset",
     "legendFormat": "{{ location }} {{ pubkey }}"
    }
   ]
  }
 ]
}