{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(alertmanager_build_info)"
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "singlestat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "singlestat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "singlestat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "singlestat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Notifications sent from $instance",
   "type": "graph",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$__interval])) by (integration)",
     "legendFormat": "{{ integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$__interval])) by (integration)",
     "legendFormat": "Failed {{ integration }}"
    }
   ]
  },
  {
   "title": "Notification durations per integration on $instance",
   "type": "graph",
   "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]))) by (integration)",
     "legendFormat": "0.9q {{ integration }}"
    },
    {
     "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]))) by (integration)",
     "legendFormat": "0.99q  {{ integration }}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active alerts in $instance",
   "type": "graph",
   "description": "Number of alerts by state such as `active`, `suppressed` etc.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Received alerts by status for $instance",
   "type": "graph",
   "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$instance\"}[$__interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nf log queries count for $instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Nf log query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Nf log query errors"
      }
     ]
    },
    {
     "title": "Nf log query duration for $instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Nf log query duration"
      }
     ]
    },
    {
     "title": "Nf log snapshot size for $instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log snapshot duration for $instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__interval]) / rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log Go GC time for $instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "alertmanager_nflog_gc_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Cluster joined peers"
      }
     ]
    }
   ]
  },
  { "title": "Silences", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Silences count by state on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Silences query count on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(alertmanager_silences_queries_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Silecnces query count"
    },
    {
     "expr": "increase(alertmanager_silences_query_errors_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Silecnces query fails"
    }
   ]
  },
  {
   "title": "Silences query duration on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Silecnces query duration"
    }
   ]
  },
  {
   "title": "Silences snapshot size on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences_snapshot_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Silecnces snapshot size"
    }
   ]
  },
  {
   "title": "Silences snapshot duration on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences_snapshot_duration_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "Silecnces snapshot duration"
    }
   ]
  },
  {
   "title": "Silences GC duraton on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences_gc_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "Silecnces GC  duration"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU usage/s for $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage for $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  }
 ]
}