{
 "title": "Blackbox Exporter",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "location", "label": "Location", "query": { "query": "label_values(up, location)" } }
  ]
 },
 "panels": [
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Internet Error Rate 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time((probe_success{location=~\"$location\",job=\"icmp-internet\"} == 0)[24h:1m]) * 100 / count_over_time((probe_success{location=~\"$location\",job=\"icmp-internet\"})[24h:1m]) or vector(0)",
     "legendFormat": "Location: {{ location }}"
    }
   ]
  },
  {
   "title": "VPN Error Rate 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time((probe_success{location=~\"$location\",job=\"icmp-vpn\"} == 0)[24h:1m]) * 100 / count_over_time((probe_success{location=~\"$location\",job=\"icmp-vpn\"})[24h:1m]) or on() vector(0)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (location) (avg_over_time(probe_icmp_duration_seconds{job=\"icmp-internet\",phase=\"rtt\"}[15m]))",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Icmp Errors 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(min_over_time(probe_success{location=~\"$location\"}[24h]) == 0)",
     "legendFormat": "{{instance}}, {{ location }}"
    }
   ]
  },
  {
   "title": "Currently Failing Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_success == 0) or vector(0)",
     "legendFormat": "Count"
    }
   ]
  },
  { "title": "ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (location) (avg_over_time(probe_icmp_duration_seconds{job=\"icmp-internet\",phase=\"rtt\"}[1h]))",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Failures During 24h",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "min_over_time(probe_success{location=~\"$location\"}[24h]) == 0",
     "legendFormat": "{{instance}}, {{ location }}"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"icmp-internet\",location=~\"$location\"}",
     "legendFormat": "{{instance}}, {{ location }}"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{location=~\"$location\",job=\"icmp-internal\"}",
     "legendFormat": "{{instance}}, {{ location }}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "HTTP connect duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Probes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "probe_success{location=~\"$location\",job=\"blackbox_tcp\"}",
     "legendFormat": "{{instance}}, {{ location }}"
    }
   ]
  },
  {
   "title": "ICMP Probes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "probe_success{location=~\"$location\",job=~\"^icmp.*\"}",
     "legendFormat": "{{instance}}, {{ location }}"
    }
   ]
  },
  {
   "title": "Used IP protocol",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "probe_ip_protocol", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}