{
 "title": "Exporters",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Unhealthy Exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "count(up == 0)" }
   ]
  },
  {
   "title": "Total jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    { "expr": "count(count by (job) (up))" }
   ]
  },
  {
   "title": "Unhealthy Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (job) (up == 0))"
    }
   ]
  },
  {
   "title": "Exporters Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up == 0)", "legendFormat": "Unreachable exporters" },
    { "expr": "count(up)", "legendFormat": "Defined exporters" }
   ]
  },
  {
   "title": "Exporters Job Healthiness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - count(up == 0) by (job) / count(up) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Exporters by Job",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Unreachable",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "up == 0", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}