{
 "title": "Systemd Services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instance, name) (node_systemd_unit_state))"
    }
   ]
  },
  {
   "title": "Services running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Services not active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{state=\"active\"} == 0)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Services Overview",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\"}",
     "legendFormat": "{{name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Services Not Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{state!=\"active\"} > 0",
     "legendFormat": "{{name }}@{{instance}}"
    }
   ]
  }
 ]
}