{
 "title": "Gobot PIR",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(gobot_pir_version, location)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": {
     "query": "label_values(gobot_pir_stats_events_per_interval, interval)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sensor Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Motions / Interval",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(gobot_pir_stats_events_per_interval{location=~\"$location\",interval=~\"$interval\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Distribution 24h",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[24h]) * 100 / sum(increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[24h]))",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Last Motion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(time() - gobot_pir_sensor_motions_detected_timestamp_seconds{location=~\"$location\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "MQTT Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(gobot_pir_mqtt_messages_published_total[1h])",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  }
 ]
}