{
 "title": "Gobot Lux",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(gobot_lux_sensor_brightness_level_percent, location)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": {
     "query": "label_values(gobot_lux_stats_delta_per_interval_percent, interval)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brightness",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(gobot_lux_sensor_brightness_level_percent{location=~\"$location\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Lux",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (location) (gobot_lux_sensor_brightness_level_percent)",
     "legendFormat": "{{location}}/{{ placement }}"
    }
   ]
  },
  {
   "title": "Lux",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gobot_lux_sensor_brightness_level_percent{location=~\"$location\"}",
     "legendFormat": "{{location}}/{{ placement }}"
    }
   ]
  },
  {
   "title": "Brightness interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gobot_lux_stats_avg_per_interval_percent{location=~\"$location\",interval=~\"$interval\"}",
     "legendFormat": "{{location}}/{{placement}} {{interval}}"
    }
   ]
  },
  { "title": "Operational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MQTT Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(gobot_lux_mqtt_messages_published_total[$__rate_interval])",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "gobot_lux_stats_delta_per_interval_percent{interval=~\"$interval\"}",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Slice Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "gobot_lux_stats_slice_entries_total",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  }
 ]
}