{
 "title": "Gobot BME280",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(gobot_bme280_heartbeat_timestamp_seconds, location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Min/Max", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (location) (gobot_bme280_sensor_temperature_celsius)",
     "legendFormat": "{{location}}/max"
    },
    {
     "expr": "min by (location) (gobot_bme280_sensor_temperature_celsius)",
     "legendFormat": "{{location}}/min"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "max by (location) (gobot_bme280_sensor_humidity_percent)",
     "legendFormat": "Max {{location}}"
    },
    {
     "expr": "min by (location) (gobot_bme280_sensor_humidity_percent)",
     "legendFormat": "Min {{location}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gobot_bme280_sensor_temperature_celsius{location=~\"$location\"}",
     "legendFormat": "{{location}}/{{ placement }}"
    }
   ]
  },
  {
   "title": "AVG Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (location) (gobot_bme280_sensor_temperature_celsius{location=~\"$location\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "gobot_bme280_sensor_humidity_percent",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg by (location) (gobot_bme280_sensor_humidity_percent)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  { "title": "Operational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Publishes MQTT Messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sensor Read Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(gobot_bme280_sensor_reading_errors_total[60m])",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Last Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - gobot_bme280_heartbeat_timestamp_seconds",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  }
 ]
}