{
 "title": "Sensors Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "label_values(gobot_bme280_sensor_pressure_pa, location)"
    }
   },
   {
    "name": "interval_pir",
    "query": {
     "query": "label_values(gobot_pir_stats_events_per_interval, interval)"
    }
   },
   {
    "name": "interval_lux",
    "query": {
     "query": "label_values(gobot_lux_stats_avg_per_interval_percent, interval)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(gobot_bme280_sensor_temperature_celsius{location=~\"$location\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(gobot_bme280_sensor_humidity_percent{location=~\"$location\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sort_desc(gobot_bme280_sensor_temperature_celsius{location=~\"$location\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sort_desc(gobot_bme280_sensor_humidity_percent{location=~\"$location\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Brightness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(gobot_lux_stats_avg_per_interval_percent{location=~\"$location\",interval=~\"$interval_lux\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Movements",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(gobot_pir_stats_events_per_interval{location=~\"$location\",interval=~\"$interval_pir\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Brightness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(gobot_lux_stats_avg_per_interval_percent{location=~\"$location\",interval=~\"$interval_lux\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  },
  {
   "title": "Movements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc(gobot_pir_stats_events_per_interval{location=~\"$location\",interval=~\"$interval_pir\"})",
     "legendFormat": "{{location}}/{{placement}}"
    }
   ]
  }
 ]
}