{
 "title": "Dyndns",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(dyndns_start_time_seconds, location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IP Successful Resolves 15m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(dyndns_client_ip_resolved_successful_total[15m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Changes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(dyndns_client_reconcilers_pending_changes_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients In Confirmed State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(dyndns_client_current_state_bool{state=\"ipConfirmedState\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disconnected Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(dyndns_mqtt_brokers_connected_total == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(dyndns_mqtt_brokers_configured_total{location=~\"$location\"})",
     "legendFormat": "Configured {{instance}}"
    },
    {
     "expr": "min(dyndns_mqtt_brokers_connected_total{location=~\"$location\"})",
     "legendFormat": "Connected {{instance}}"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(time() - dyndns_start_time_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Message Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(dyndns_server_message_validations_failed_total[$__rate_interval]))",
     "legendFormat": "Validation Errors"
    },
    {
     "expr": "sum (increase(dyndns_server_message_parsing_failed_total[$__rate_interval]))",
     "legendFormat": "Parsing Errors"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Last State Transition",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (host) (time() - dyndns_client_state_changed_timestamp)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dyndns_client_current_state_bool == 1",
     "legendFormat": "{{host }}: {{state}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, dyndns_client_resolver_response_time_seconds_bucket{location=~\"$location\"})",
     "legendFormat": "{{location}} / {{ resolver }}"
    }
   ]
  },
  {
   "title": "Last Check",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - dyndns_client_ip_resolves_last_check_timestamp_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Resolve Errors 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(dyndns_client_ip_resolves_errors_total[24h])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "DNS Propagation Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(dyndns_server_dns_propagation_requests_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last DNS Propagation Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - dyndns_server_dns_propagation_request_timestamp_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(dyndns_server_messages_received_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(dyndns_server_message_validations_failed_total[$__rate_interval]))",
     "legendFormat": "Validation Errors"
    },
    {
     "expr": "sum (increase(dyndns_server_message_parsing_failed_total[$__rate_interval]))",
     "legendFormat": "Parsing Errors"
    }
   ]
  }
 ]
}