{
 "title": "Fail2ban",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(fail2ban_banned_current, instance)"
   },
   {
    "name": "jail",
    "label": "Jail",
    "query": "label_values(fail2ban_banned_current, jail)"
   }
  ]
 },
 "panels": [
  {
   "title": "Banned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(fail2ban_banned_current)", "legendFormat": "{{ jail }}" }
   ]
  },
  {
   "title": "Banned 1h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(fail2ban_banned_current[1h])))"
    }
   ]
  },
  {
   "title": "Banned 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(fail2ban_banned_current[24h])))"
    }
   ]
  },
  {
   "title": "Banned 7d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(fail2ban_banned_current[7d])))"
    }
   ]
  },
  {
   "title": "Failed 1h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(fail2ban_failed_total[1h])))"
    }
   ]
  },
  {
   "title": "Failed 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(fail2ban_failed_total[24h])))"
    }
   ]
  },
  {
   "title": "Failed 7d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(fail2ban_failed_total[7d])))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Bans per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(fail2ban_banned_total{instance=~\"$instance\",jail=~\"$jail\"}[1h])",
     "legendFormat": "{{ jail }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Client Failures [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(fail2ban_failed_total{instance=~\"$instance\",jail=~\"$jail\"}[1h])",
     "legendFormat": "{{ jail }}, {{ instance }}"
    }
   ]
  },
  { "title": "Banned Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Banned Current Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_banned_current{instance=~\"$instance\",jail=~\"$jail\"}",
     "legendFormat": "{{ jail }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Banned Total Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_banned_total{instance=~\"$instance\",jail=~\"$jail\"}",
     "legendFormat": "{{ jail }}, {{ instance }}"
    }
   ]
  },
  { "title": "Failed Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Failed Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_failed_current{instance=~\"$instance\",jail=~\"$jail\"}",
     "legendFormat": "{{ jail }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Failed Clients Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_failed_total{instance=~\"$instance\",jail=~\"$jail\"}",
     "legendFormat": "{{ jail }}, {{ instance }}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fail2ban_errors_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Last timestamp",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - fail2ban_timestamp_seconds",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}