{
 "title": "Kernel Overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_boot_time_seconds, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "<= 24 hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(abs(node_boot_time_seconds{job=~\"$job\"} - time())  < 86400))"
    }
   ]
  },
  {
   "title": "<= 3 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(abs(node_boot_time_seconds{job=~\"$job\"} - time())  < 259200))"
    }
   ]
  },
  {
   "title": ">= 3 month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(abs(node_boot_time_seconds{job=~\"$job\"} - time())  > 2592000 * 3))"
    }
   ]
  },
  {
   "title": "Autoreboot Checks",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(time() - max(conditional_reboot_start_time_seconds) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": ">= 1 month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(abs(node_boot_time_seconds{job=~\"$job\"} - time())  > 2592000))"
    }
   ]
  },
  {
   "title": ">= 2 month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(abs(node_boot_time_seconds{job=~\"$job\"} - time())  > 2592000 * 2))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(abs(node_boot_time_seconds{job=~\"$job\"} - time()))",
     "legendFormat": "{{ location }},{{ instance }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table-old",
   "gridPos": { "h": 24, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "node_boot_time_seconds{job=~\"$job\"} - time()"
    }
   ]
  },
  {
   "title": "Uname Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kernel Overview",
   "type": "table-old",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"}"
    }
   ]
  }
 ]
}