{
 "title": "libvirt",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(libvirt_domain_info_cpu_time_seconds_total, location)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(libvirt_domain_info_cpu_time_seconds_total, domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (instance,domain) (irate(libvirt_domain_info_cpu_time_seconds_total{location=~\"$datacenter\",domain=~\"$domain\"}[1m])) * 100",
     "legendFormat": "{{instance}}/{{domain}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Data received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(libvirt_domain_interface_stats_receive_bytes_total{location=~\"$datacenter\",domain=~\"$domain\"}[5m])",
     "legendFormat": "{{instance}}/{{domain}}"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(libvirt_domain_interface_stats_transmit_bytes_total{location=~\"$datacenter\",domain=~\"$domain\"}[1m])",
     "legendFormat": "{{instance}}/{{domain}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Data read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(libvirt_domain_block_stats_read_bytes_total{location=~\"$datacenter\",domain=~\"$domain\"}[5m])",
     "legendFormat": "{{instance}}/{{domain}}"
    }
   ]
  },
  {
   "title": "Data written",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(libvirt_domain_block_stats_write_bytes_total{location=~\"$datacenter\",domain=~\"$domain\"}[5m])",
     "legendFormat": "{{instance}}/{{domain}}"
    }
   ]
  }
 ]
}