{
 "title": "OpenBSD Router",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(openbsd_service_pid, location)"
    }
   },
   {
    "name": "interface",
    "label": "Default Route Interface",
    "query": {
     "query": "label_values(openbsd_route_default, interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{location=~\"$location\",job=\"routers\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Services Not Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openbsd_service_pid{instance=~\"$Instance\"} < 1)"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "openbsd_cpu_temp_celsius{location=~\"$location\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Internet uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openbsd_uplink_uptime_seconds{location=~\"$location\"}"
    }
   ]
  },
  {
   "title": "Data received 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(node_network_receive_bytes_total{location=~\"$location\",device=~\"$interface\"}[24h])"
    }
   ]
  },
  {
   "title": "Data transmitted 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(node_network_transmit_bytes_total{location=~\"$location\",device=~\"$interface\"}[24h])"
    }
   ]
  },
  {
   "title": "DNS uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openbsd_unbound_uptime_service_seconds{location=~\"$location\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg Cache Hits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(openbsd_unbound_num_cache_hits_total{location=~\"$location\"}[24h]) / avg_over_time(openbsd_unbound_num_queries_total{location=~\"$location\"}[24h])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Adblock Update",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - unbound_adblocker_import_timestamp{location=~\"$location\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data staleness",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - openbsd_emitter_timestamp_seconds{location=~\"$location\"}"
    }
   ]
  },
  {
   "title": "Tunnelguard Invocation",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_tunnelguard_invocation_timestamp_seconds{location=~\"$location\"}"
    }
   ]
  },
  { "title": "HW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Internet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{location=~\"$location\",device=~\"$interface\"}[5m])",
     "legendFormat": "Down"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{location=~\"$location\",device=~\"interface\"}[5m])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Wireguard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{location=~\"$location\",device=~\"wg.*\"}[5m])",
     "legendFormat": "Down {{ device }} {{ instance }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{location=~\"$location\",device=~\"wg.*\"}[5m])",
     "legendFormat": "Up {{ device }} {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",location=~\"$location\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"interrupt\",location=~\"$location\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"user\",location=~\"$location\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"irq\",location=~\"$location\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"nice\",location=~\"$location\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{location=~\"$location\",device!~'rootfs'} - node_filesystem_avail_bytes{location=~\"$location\",device!~'rootfs',job=\"routers\"}",
     "legendFormat": "{{ instance }} - {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Route Table Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_route_entries_total{location=~\"$location\"}",
     "legendFormat": "{{ location }} {{ ip }}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "openbsd_cpu_temp_celsius{location=~\"$location\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "SSH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mtail_auth_ssh_login{location=~\"$location\"}[5m])",
     "legendFormat": "Successful logins {{ instance }}"
    },
    {
     "expr": "increase(mtail_auth_ssh_failed_login{location=~\"$location\"}[5m])",
     "legendFormat": "Failed logins"
    },
    {
     "expr": "increase(mtail_auth_ssh_invalid_user{location=~\"$location\"}[5m])",
     "legendFormat": "Unknown user"
    }
   ]
  },
  {
   "title": "Logged in users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_users_logged_in_total{location=~\"$location\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Doas ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mtail_auth_doas_cmd{location=~\"$location\"}[5m])",
     "legendFormat": "{{ instance }} {{ user }}"
    }
   ]
  },
  {
   "title": "Cron ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mtail_cron_executions{location=~\"$location\"}[5m])",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Running procs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_procs_total{location=~\"$location\"}"
    }
   ]
  },
  {
   "title": "System users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_users_total{location=~\"$location\"}",
     "legendFormat": "{{ users }} {{ instance }}"
    }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Blocked packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(openbsd_pf_ipv4_packets_total{action=\"blocked\",location=~\"$location\"}[30m])",
     "legendFormat": "{{direction}}: {{ instance }}"
    }
   ]
  },
  {
   "title": "Passed packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(openbsd_pf_ipv4_packets_total{location=~\"$location\",action=\"passed\"}[5m])",
     "legendFormat": "{{action}} {{direction}}"
    }
   ]
  },
  {
   "title": "State entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_pf_state_entries{location=~\"$location\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "State inserts/removals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(openbsd_pf_state_inserts{location=~\"$location\"}[5m])",
     "legendFormat": "Inserts {{ instance }}"
    },
    {
     "expr": "increase(openbsd_pf_state_removals{location=~\"$location\"}[5m])",
     "legendFormat": "Removals {{ instance }}"
    }
   ]
  },
  {
   "title": "Searches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(openbsd_pf_state_searches{location=~\"$location\"}[5m])",
     "legendFormat": "Inserts"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "DNS queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_unbound_num_queries_total{location=~\"$location\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "openbsd_unbound_num_queries_total{location=~\"$location\"} - openbsd_unbound_num_queries_tcp_total{location=~\"$location\"}",
     "legendFormat": "UDP"
    },
    {
     "expr": "openbsd_unbound_num_queries_tcp_total{location=~\"$location\"}",
     "legendFormat": "TCP"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "openbsd_unbound_num_cache_hits_total{location=~\"$location\"} * 100 / openbsd_unbound_num_queries_total{location=~\"$location\"}",
     "legendFormat": "Cache hits {{ instance }}"
    }
   ]
  },
  {
   "title": "DNS Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openbsd_unbound_expired_entries_total{location=~\"$location\"}",
     "legendFormat": "Expired {{instance}}"
    },
    {
     "expr": "openbsd_unbound_prefetched_total{location=~\"$location\"}",
     "legendFormat": "Prefetched {{ instance }}"
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mtail_dhcpd_request_total{location=~\"$location\"}[5m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mtail_dhcpd_lease_conflicts{location=~\"$location\"}[5m])",
     "legendFormat": "Lease conflicts"
    },
    {
     "expr": "increase(mtail_dhcpd_ip_already_in_use{location=~\"$location\"}[5m])",
     "legendFormat": "IP already in use"
    },
    {
     "expr": "increase(mtail_dhcpd_invalid_state_transition{location=~\"$location\"}[5m])",
     "legendFormat": "Invalid state trans"
    },
    {
     "expr": "increase(mtail_dhcpd_unknown_subnet{location=~\"$location\"}[5m])",
     "legendFormat": "Unknown subnets"
    }
   ]
  }
 ]
}