{
 "title": "OpenWrt",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_openwrt_info, instance)"
    }
   },
   {
    "name": "devices",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Release",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_openwrt_info" }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_openwrt_info" }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_openwrt_info" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(wifi_station_signal_dbm)" }
   ]
  },
  {
   "title": "Received bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "repeat": "devices",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-increase(node_network_receive_bytes_total{instance=\"$instance\"}[5m])"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=\"$instance\"}[5m])"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 454 } },
  {
   "title": "WiFi Bitrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 455 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wifi_network_bitrate" }
   ]
  },
  {
   "title": "WiFi quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 455 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "wifi_network_quality" }
   ]
  },
  {
   "title": "WiFi Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 463 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    { "expr": "wifi_network_noise_dbm" }
   ]
  },
  {
   "title": "WiFi Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 463 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    { "expr": "wifi_network_signal_dbm" }
   ]
  }
 ]
}