{
 "title": "Smartctl",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "location", "label": "Location", "query": { "query": "label_values(up, location)" } }
  ]
 },
 "panels": [
  {
   "title": "Device Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_critical_warning + smartctl_device_media_errors)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spare Exceeded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((smartctl_device_available_spare > 0) <= smartctl_device_available_spare_threshold) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Spare",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(smartctl_device_available_spare > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Temp Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{device!~\"^nvme.*\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVME Temp Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(smartctl_device_temperature{device=~\"^nvme.*\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{location=~\"$location\"}",
     "legendFormat": "Critical Warnings: {{instance}} - {{ device }}"
    },
    {
     "expr": "smartctl_device_media_errors{location=~\"$location\"}",
     "legendFormat": "Media Errors: {{instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Spare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{location=~\"$location\"} > 0",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(smartctl_device_power_cycle_count)",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Power On",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{location=~\"$location\"}",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{location=~\"$location\"}",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  }
 ]
}