{
 "title": "Wireguard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(wireguard_bytes_received_total, instance)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "label_values(wireguard_bytes_received_total, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tunnelguard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Invokation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_tunnelguard_invocation_timestamp_seconds",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Last Handshake",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_tunnelguard_peer_handshake_timestamp_seconds",
     "legendFormat": "{{ location }} {{ pubkey }}"
    }
   ]
  },
  {
   "title": "Tunnel Resets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wireguard_tunnelguard_peer_reset",
     "legendFormat": "{{ location }} {{ pubkey }}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Hearbeat",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_heartbeat_timestamp",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Defined peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (addr) (wireguard_bytes_received_total))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Handshake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - wireguard_handshake_timestamp",
     "legendFormat": "{{nicename}} {{addr}}@{{device}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(wireguard_bytes_received_total[1m])",
     "legendFormat": "{{nicename}} {{addr}}@{{device}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(wireguard_bytes_sent_total[1m])",
     "legendFormat": "{{nicename}} {{addr}}@{{device}}"
    }
   ]
  },
  {
   "title": "Received total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wireguard_bytes_received_total",
     "legendFormat": "{{nicename}} {{addr}}@{{device}}"
    }
   ]
  },
  {
   "title": "Sent total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wireguard_bytes_sent_total",
     "legendFormat": "{{nicename}} {{addr}}@{{device}}"
    }
   ]
  }
 ]
}