{
 "title": "Gobot Lux",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(gobot_lux_version, location)"
    }
   },
   {
    "name": "placement",
    "label": "Placement",
    "query": {
     "query": "label_values(gobot_lux_sensor_brightness_level, placement)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": {
     "query": "label_values(gobot_lux_stats_delta_per_interval, interval)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(gobot_lux_sensor_brightness_level)",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Current AVG",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(gobot_lux_sensor_brightness_level)",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - gobot_lux_heartbeat_seconds",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gobot_lux_version", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Process Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gobot-lux\",location=~\"$location\"}[$__rate_interval]) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"gobot-lux\",location=~\"$location\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  { "title": "Brightness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Brightness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gobot_lux_sensor_brightness_level{location=~\"$location\",placement=~\"$placement\"}",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(gobot_lux_sensor_brightness_level) by (location)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "gobot_lux_stats_avg_per_interval{location=~\"$location\",placement=~\"$placement\",interval=~\"$interval\"}",
     "legendFormat": "{{ location }} / {{ placement }} {{ interval }}"
    }
   ]
  },
  { "title": "Delta $interval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "interval" },
  {
   "title": "Delta $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "gobot_lux_stats_delta_per_interval{location=~\"$location\",placement=~\"$placement\",interval=~\"$interval\"}",
     "legendFormat": "{{ interval }} {{ location }}/{{ placement }}"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "MQTT Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(gobot_lux_mqtt_messages_published_total{location=~\"$location\",placement=~\"$placement\"}[5m])",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "MQTT Message Send Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "increase(gobot_lux_mqtt_message_publish_errors{location=~\"$location\",placement=~\"$placement\"}[5m]) or vector(0)",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  }
 ]
}