{
 "title": "Gobot Motions",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(gobot_pir_version, location)"
    }
   },
   {
    "name": "placement",
    "label": "Placement",
    "query": {
     "query": "label_values(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}, placement)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": {
     "query": "label_values(gobot_pir_stats_events_per_interval{location=~\"$location\",placement=~\"$placement\"}, interval)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Motions 30m",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[30m]))",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Motions 1h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[1h]))",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Motions 3h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[3h]))",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Motions 12h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[12h]))",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Motions 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\"}[24h]))",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Last Motion",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(time() - gobot_pir_sensor_motions_detected_timestamp_seconds{location=~\"$location\",placement=~\"$placement\"})",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heartbeat",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - sort_desc(gobot_pir_heartbeat_timestamp_seconds{location=~\"$location\",placement=~\"$placement\"})",
       "legendFormat": "{{ location }} / {{ placement }}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "gobot_pir_version", "legendFormat": "{{ version }}" }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"gobot-pir\",location=~\"$location\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gobot-pir\",location=~\"$location\"}[$__rate_interval]) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Stats Slice Entries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gobot_pir_stats_slice_entries_total{location=~\"$location\",placement=~\"$placement\"}",
       "legendFormat": "{{ placement }}"
      }
     ]
    }
   ]
  },
  { "title": "Liveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Motions Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(gobot_pir_sensor_motions_detected_total{location=~\"$location\",placement=~\"$placement\"}[3m])",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  { "title": "Stats $interval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "interval" },
  {
   "title": "Motion Stats $interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gobot_pir_stats_events_per_interval{interval=~\"$interval\",location=~\"$location\",placement=~\"$placement\"}",
     "legendFormat": "{{ interval }} {{ placement }}"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MQTT Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(gobot_pir_mqtt_messages_published_total{location=~\"$location\",placement=~\"$placement\"}[3m])",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  },
  {
   "title": "MQTT Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(gobot_pir_mqtt_messages_publish_errors_total{location=~\"$location\",placement=~\"$placement\"}[3m]) or vector(0) ",
     "legendFormat": "{{ location }} / {{ placement }}"
    }
   ]
  }
 ]
}