{
 "title": "Home Assistant",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(homeassistant_binary_sensor_state, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(homeassistant_sensor_battery_percent{instance=~\"$Instance\"})",
     "legendFormat": "{{ location }} / {{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Workday",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{instance=~\"$Instance\",entity=\"binary_sensor.workday\"}"
    }
   ]
  },
  {
   "title": "State Changes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(homeassistant_state_change_total{instance=~\"$Instance\",friendly_name!~\"(.*(temperature|humidity|brightness)|(^presence.*)|^Sun$)\"}[15m]))"
    }
   ]
  },
  {
   "title": "Automations",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(homeassistant_automation_triggered_count_total{instance=~\"$Instance\",instance=~\"$Instance\"}[5m]))"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$Instance\"}[$__interval]) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$Instance\"}",
     "legendFormat": "Virtual mem"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$Instance\"}",
     "legendFormat": "Resident mem"
    }
   ]
  },
  {
   "title": "Python version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{instance=~\"$Instance\"}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Binary sensor state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "yaxes": [
    { "format": "bool_on_off" }
   ],
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{instance=~\"$Instance\",entity!~\"binary_sensor.(presence_.*|workday)\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Presence State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "yaxes": [
    { "format": "bool_on_off" }
   ],
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{instance=~\"$Instance\",entity=~\"binary_sensor.presence_(bedroom|office|corridor|livingroom)\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "homeassistant_light_brightness_percent{instance=~\"$Instance\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bool_on_off" }
   ],
   "targets": [
    {
     "expr": "homeassistant_switch_state{instance=~\"$Instance\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Automations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(homeassistant_automation_triggered_count_total{instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "homeassistant_temperature_c{entity=~\"climate.thermostat_.*\"}",
       "legendFormat": "{{ friendly_name }}"
      }
     ]
    },
    {
     "title": "Actual temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "homeassistant_current_temperature_c{entity=~\"climate.thermostat_.*\"}",
       "legendFormat": "{{ friendly_name }}"
      }
     ]
    },
    {
     "title": "Temperature delta",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "homeassistant_current_temperature_c{entity=~\"climate.thermostat_.*\"} - homeassistant_temperature_c{entity=~\"climate.thermostat_.*\"}",
       "legendFormat": "{{ friendly_name }}"
      }
     ]
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Battery level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{instance=~\"$Instance\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  }
 ]
}