---
services:
  grafana:
    image: grafana/grafana:11.0.1
    restart: always
    ports:
      - "3000:3000"

  vault:
    image: hashicorp/vault:1.19.0
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
