{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Vault Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{}) or vector(3)"
    }
   ]
  },
  {
   "title": "House Porto",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature 1d",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "min(gobot_bme280_sensor_temperature_celsius{location=\"pt\"})",
       "legendFormat": "Min"
      },
      {
       "expr": "max(gobot_bme280_sensor_temperature_celsius{location=\"pt\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Humidity 1d",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "min(gobot_bme280_sensor_humidity_percent{location=\"pt\"})",
       "legendFormat": "Min"
      },
      {
       "expr": "max(gobot_bme280_sensor_humidity_percent{location=\"pt\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Firing Alerts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\",location=\"pt\"})",
       "legendFormat": "{{ alertstate }}"
      }
     ]
    }
   ]
  },
  { "title": "House Düsseldorf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.presence_house\",location=\"dd\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Lux 1d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(gobot_lux_sensor_brightness_level{location=\"dd\"})",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Temperature 1d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(gobot_bme280_sensor_temperature_celsius{location=\"dd\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(gobot_bme280_sensor_temperature_celsius{location=\"dd\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Humidity 1d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(gobot_bme280_sensor_humidity_percent{location=\"dd\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(gobot_bme280_sensor_humidity_percent{location=\"dd\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Motions 1d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(gobot_pir_sensor_motions_detected_total{location=\"dd\"}[24h]))",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Automations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(homeassistant_automation_triggered_count_total[12h]))"
    }
   ]
  },
  {
   "title": "State Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(homeassistant_state_change_total[6h]))"
    }
   ]
  },
  {
   "title": "Lights On",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(homeassistant_light_brightness_percent > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",location=\"dd\"})",
     "legendFormat": "{{ alertstate }}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DSL Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (location) (avg_over_time(probe_success{job=\"icmp-internet\"}[1h]) * 100)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Latency DSL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (location) (avg_over_time(probe_icmp_duration_seconds{job=\"icmp-internet\",phase=\"rtt\"}[1h]))",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "VPN Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (location) (avg_over_time(probe_success{job=\"icmp-vpn\"}[1h]) * 100)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Latency VPN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (location) (avg_over_time(probe_icmp_duration_seconds{job=\"icmp-vpn\",phase=\"rtt\"}[1h]))",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Backups Ok",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rclone_backup_timestamp_seconds{outcome=~\"no-work|success\"})",
     "legendFormat": "{{ location }} {{ identifier }}"
    }
   ]
  },
  {
   "title": "Backups Fail",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rclone_backup_timestamp_seconds{outcome!~\"no-work|success\"}) or vector(0)",
     "legendFormat": "{{ location }} {{ identifier }}"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or vector(0)",
     "legendFormat": "{{ alertstate }}"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"}) or vector(0)",
     "legendFormat": "{{ alertstate }}"
    }
   ]
  },
  {
   "title": "Defined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cortex_prometheus_rule_group_rules)"
    }
   ]
  },
  {
   "title": "Sent Notifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total[3m]))"
    }
   ]
  },
  {
   "title": "Failing Notifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(increase(alertmanager_notifications_failed_total[3m]))"
    }
   ]
  },
  {
   "title": "Cortex Ingestions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(cortex_ingester_ingested_samples_total[3m])"
    }
   ]
  },
  {
   "title": "Min Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(acmevault_certificate_expiry_time) - time()"
    }
   ]
  },
  {
   "title": "Autoreboot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(autoreboot_reboot_necessary_bool > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Failing Systemd Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"failed\"} > 0) or vector(0)",
     "legendFormat": "{{ instance }} {{ name }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "ALERTS > 0" }
   ]
  }
 ]
}