{
 "title": "Vault Approles",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(vault_approle_rotation_success_bool, location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Defined Approles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vault_approle_rotation_invocation_timestamp_seconds{location=~\"$location\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rotation Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vault_approle_rotation_success_bool{location=~\"$location\"} != 1) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Last Invocation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(time() - vault_approle_rotation_invocation_timestamp_seconds{location=~\"$location\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Validity Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, vault_approle_rotation_validity_period_percent_total{location=~\"$location\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "avg(vault_approle_rotation_validity_period_percent_total{location=~\"$location\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(vault_approle_rotation_validity_period_percent_total{location=~\"$location\"})",
     "legendFormat": "Min"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Next 5 Certs to expire",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(vault_approle_rotation_validity_period_percent_total{location=~\"$location\"})",
     "legendFormat": "{{role_name}}"
    }
   ]
  },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "vault_approle_rotation_success_bool{location=~\"$location\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}