{
 "title": "Vault PKI CLI",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(vault_pki_cli_cert_expiry_seconds, location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runtime Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vault_pki_cli_success_bool{location=~\"$location\"} != 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, vault_pki_cli_cert_expiry_seconds{location=~\"$location\"} / 1000 - time())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Managed Certs Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vault_pki_cli_success_bool{location=~\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Cert Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vault_pki_cli_cert_lifetime_seconds_total{location=~\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cert Parse Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vault_pki_cli_cert_parse_errors_total{location=~\"$location\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Certificate Expiry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vault_pki_cli_cert_expiry_seconds{location=~\"$location\"} / 1000 - time()",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invokations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, time() - vault_pki_cli_run_timestamp_seconds{location=~\"$location\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "avg(time() - vault_pki_cli_run_timestamp_seconds{location=~\"$location\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Median Lifetime Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, vault_pki_cli_cert_lifetime_seconds_total{location=~\"$location\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "avg(vault_pki_cli_cert_lifetime_seconds_total{location=~\"$location\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(vault_pki_cli_cert_lifetime_seconds_total{location=~\"$location\"})",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}