{
 "title": "Vault SSH Host Keys",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(ssh_key_signer_cert_lifetime_percent, location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cert Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssh_key_signer_success_bool == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Managed Certs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssh_key_signer_success_bool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Cert Lifetime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, ssh_key_signer_cert_lifetime_percent{location=~\"$location\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cert Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssh_key_signer_cert_lifetime_percent{location=~\"$location\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(time() - ssh_key_signer_run_timestamp_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(ssh_key_signer_cert_lifetime_seconds_total)",
     "legendFormat": "Max"
    },
    {
     "expr": "quantile(0.5, ssh_key_signer_cert_lifetime_seconds_total)",
     "legendFormat": "Median"
    },
    {
     "expr": "min(ssh_key_signer_cert_lifetime_seconds_total)",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}