{
 "title": "Fileservers",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "location", "query": "dd,ez,pt" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backups Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(time() - rclone_backup_timestamp_seconds{outcome=~\"success|no-work\"} <= 86400) or vector(0)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Backups Fails",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(time() - rclone_backup_timestamp_seconds{outcome!~\"success|no-work\"}) or vector(0)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Backups Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(time() - rclone_backup_timestamp_seconds{outcome=~\"success|no-work\"} > 86400) or vector(0)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Sync Job Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fileserver_sync_job_success == 0) or vector(0)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sync Job Invokation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - fileserver_sync_job_timestamp_seconds",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Corrupted Flacs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flacverifier_corrupt_files_total"
    }
   ]
  },
  {
   "title": "Last Flac Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - flacverifier_heartbeat_seconds"
    }
   ]
  },
  {
   "title": "Samba",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"fileservers\",name=\"smbd.service\",state=\"active\"}",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Mounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "metrics_emitter_gocryptfs_mount_active_bool{dir=\"/srv/files/media\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Release",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"fileservers\"}",
     "legendFormat": "{{ location }} / {{ release }}"
    }
   ]
  },
  {
   "title": "Last Successfull Loot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Offline Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(time() - metrics_emitter_last_successful_offline_backup_timestamp_seconds)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Machine Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ram Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NAS Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Root Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(node_filesystem_free_bytes{job=\"nas\",mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{job=\"nas\",mountpoint=\"/\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(node_filesystem_avail_bytes{job=\"nas\",location=~\"$location\",mountpoint=\"/mnt/wdred\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(time() - node_boot_time_seconds{job=\"nas\",location=~\"$location\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "CPU over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"nas\",mode=\"idle\",location=~\"$location\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * (node_memory_MemTotal_bytes{location=~\"$location\",job=\"nas\"} - node_memory_MemFree_bytes{location=~\"$location\",job=\"nas\"} - (node_memory_Cached_bytes{location=~\"$location\",job=\"nas\"} + node_memory_Buffers_bytes{location=~\"$location\",job=\"nas\"})) / node_memory_MemTotal_bytes{location=~\"$location\",job=\"nas\"})",
     "legendFormat": "free {{location}}"
    }
   ]
  },
  {
   "title": "Disk Reads / Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{job=\"nas\",location=~\"$location\"}[5m])",
     "legendFormat": "{{location}}/{{device}}"
    }
   ]
  },
  {
   "title": "Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{job=\"nas\",location=~\"$location\"}[5m])",
     "legendFormat": "{{location}}/{{device}}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successful Backups",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(time() - metrics_emitter_last_successful_offline_backup_timestamp_seconds)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - rclone_backup_timestamp_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}