{
 "title": "Media",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rclone Sync",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - rclone_backup_timestamp_seconds{outcome=~\"success|no-work\"}",
     "legendFormat": "{{ identifier }}: {{ outcome }}"
    }
   ]
  },
  {
   "title": "Loot Fetch",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - remote_move_timestamp_seconds{outcome=\"success\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Nas Exporter",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - nas_files_heartbeat_timestamp_seconds",
     "legendFormat": "Last invokation"
    }
   ]
  },
  {
   "title": "Rclone Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - rclone_usage_heartbeat_seconds",
     "legendFormat": "{{ drive }}"
    }
   ]
  },
  {
   "title": "Pending Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"incoming\"}"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Nas Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(nas_files_size_bytes)" }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"movies\"}"
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"shows\"}"
    }
   ]
  },
  {
   "title": "Music",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nas_files_size_bytes{kind=\"music\"})"
    }
   ]
  },
  {
   "title": "Books",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nas_files_size_bytes{kind=\"books\"})"
    }
   ]
  },
  {
   "title": "Photos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"photos\"}"
    }
   ]
  },
  {
   "title": "Games",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"games\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"documents\"}"
    }
   ]
  },
  {
   "title": "Scans",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"scans\"}"
    }
   ]
  },
  { "title": "Rclone Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GDrive Use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_usage_bytes{drive=\"gdrive\",state=\"used\"}"
    }
   ]
  },
  {
   "title": "GDrive Trash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_usage_bytes{drive=\"gdrive\",state=\"trashed\"}"
    }
   ]
  },
  {
   "title": "Dropbox Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_usage_bytes{drive=\"dropbox\",state=\"used\"}"
    }
   ]
  },
  {
   "title": "Dropbox Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rclone_usage_bytes{drive=\"dropbox\",state=\"free\"}"
    }
   ]
  },
  { "title": "Rclone Synchronizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Syncronized files",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_backup_files_transferred_total",
     "legendFormat": "{{identifier}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_backup_transferred_bytes",
     "legendFormat": "{{ identifier }}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rclone_backup_runtime_seconds", "legendFormat": "{{ identifier }}" }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rclone_backup_transferred_bytes / rclone_backup_runtime_seconds",
     "legendFormat": "{{ identifier }}"
    }
   ]
  },
  {
   "title": "Syncronized files",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rclone_backup_files_transferred_total",
     "legendFormat": "{{identifier}}:{{direction}}"
    }
   ]
  },
  { "title": "Fetched files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Runtime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "remote_move_runtime_seconds" }
   ]
  },
  {
   "title": "Transferred",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 41 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "remote_move_transferred_bytes" }
   ]
  },
  {
   "title": "Synced files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "remote_move_files_synced_total", "legendFormat": "{{host}}:{{src}} -> {{dst}}" }
   ]
  },
  {
   "title": "Transferred Files",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "remote_move_files_synced_total" }
   ]
  },
  {
   "title": "Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "remote_move_transferred_bytes / remote_move_runtime_seconds"
    }
   ]
  },
  { "title": "Media", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Movies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"movies\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"movies\"}"
    }
   ]
  },
  {
   "title": "Books",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"books\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"books\"}"
    }
   ]
  },
  {
   "title": "Shows",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"shows\",type=\"shows\"}",
     "legendFormat": "Shows"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"shows\",type=\"episodes\"}",
     "legendFormat": "Episodes"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"shows\"}"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"music\",type=\"albums\"}",
     "legendFormat": "{{ codec }}"
    }
   ]
  },
  {
   "title": "Songs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{type=\"songs\"}",
     "legendFormat": "{{ codec }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"music\"}",
     "legendFormat": "{{ codec }}"
    }
   ]
  },
  {
   "title": "Corrupt Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flacverifier_corrupt_files_total"
    }
   ]
  },
  {
   "title": "Scanned Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flacverifier_scanned_files_total"
    }
   ]
  },
  {
   "title": "Scanned Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - flacverifier_heartbeat_seconds"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flacverifier_timestamp_seconds" }
   ]
  },
  { "title": "Photos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Photos",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"photos\"}",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"photos\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Games", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Games",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"games\"}",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"games\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"documents\"}",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"documents\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Scans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Scans",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nas_files_count_total{kind=\"scans\"}",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nas_files_size_bytes{kind=\"scans\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}