{
 "title": "sc-agent",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "dc",
    "label": "Datacenter",
    "query": {
     "query": "label_values(sc_agent_heartbeat_timestamp_seconds,datacenter)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sc_agent_acme_errors_total[$__range])) + \nsum(increase(sc_agent_pki_errors_total[$__range])) + \nsum(increase(sc_agent_ssh_errors_total[$__range])) + \nsum(increase(sc_agent_invocation_errors_total[$__range])) + \nsum(increase(sc_agent_http_replication_errors_total[$__range])) + \nsum(increase(sc_agent_adapters_http_tls_errors_total[$__range])) + \nsum(increase(sc_agent_vault_secrets_replication_errors_total[$__range])) +\nsum(increase(sc_agent_release_watcher_update_check_errors_total[$__range])) or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Next PKI Cert Expiration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(sc_agent_pki_expiry_timestamp_seconds{datacenter=~\"$dc\"}) by (datacenter)) - time()",
     "legendFormat": "{{datacenter }}"
    }
   ]
  },
  {
   "title": "Next SSH Cert Expiration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(sc_agent_ssh_expiry_timestamp_seconds{datacenter=~\"$dc\"}) by (datacenter)) - time()",
     "legendFormat": "{{datacenter }}"
    }
   ]
  },
  {
   "title": "Next ACME Cert Expiration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(sc_agent_acme_expiry_timestamp_seconds{datacenter=~\"$dc\"}) by (datacenter)) - time()",
     "legendFormat": "{{datacenter }}"
    }
   ]
  },
  {
   "title": "Agents Monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(count(sc_agent_heartbeat_timestamp_seconds{datacenter=~\"$dc\"}) by (datacenter))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updates Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sc_agent_release_watcher_update_available_bool{datacenter=~\"$dc\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ACME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cert Expiration",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(sc_agent_acme_expiry_timestamp_seconds{datacenter=~\"$dc\"} - time())",
     "legendFormat": "{{cn}} {{ instance }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(sc_agent_acme_errors_total{datacenter=~\"$dc\"}[$__range])) by (instance) * 100 /\nsum(increase(sc_agent_acme_requests_total{datacenter=~\"$dc\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Secret Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Replications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(sc_agent_vault_secrets_replication_secrets_read_total{datacenter=~\"$dc\"}[$__range])",
     "legendFormat": "{{instance}} {{ path }}"
    }
   ]
  },
  {
   "title": "Replication Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase(sc_agent_vault_secrets_replication_errors_total{datacenter=~\"$dc\"}[$__range]) or vector(0)",
     "legendFormat": "{{instance}} {{ path }}"
    }
   ]
  },
  { "title": "HTTP Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "HTTP Replication Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(sc_agent_http_replication_errors_total{datacenter=~\"$dc\"}[$__range]) or vector(0)",
     "legendFormat": "{{error}} {{ id }} {{ instance}}"
    }
   ]
  },
  {
   "title": "Checksums",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sc_agent_http_replication_hash_value_total{datacenter=~\"$dc\"}",
     "legendFormat": "{{error}} {{ id }} {{ instance}}"
    }
   ]
  },
  { "title": "PKI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cert Expiration",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(sc_agent_pki_expiry_timestamp_seconds{datacenter=~\"$dc\"} - time())",
     "legendFormat": "{{cn}} {{ instance }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(sc_agent_pki_errors_total{datacenter=~\"$dc\"}[$__range])) by (instance) * 100 /\nsum(increase(sc_agent_pki_requests_total{datacenter=~\"$dc\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "SSH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Cert Expiration",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(sc_agent_ssh_expiry_timestamp_seconds{datacenter=~\"$dc\"} - time())",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(sc_agent_ssh_errors_total[$__range])) by (instance) * 100 /\nsum(increase(sc_agent_ssh_requests_total[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Vault Approles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Lifetime",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(sc_agent_vault_approle_secret_id_ttl_percent{datacenter=~\"$dc\"})",
     "legendFormat": "{{instance}} {{ secret_id_file }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "increase(sc_agent_vault_approle_secret_id_rotation_errors_total{datacenter=~\"$dc\"}[$__range])",
     "legendFormat": "{{instance }} {{error}}"
    }
   ]
  },
  { "title": "Vault Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Login Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "increase(sc_agent_vault_renewal_login_errors_total{datacenter=~\"$dc\"}[$__range])",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "# Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "increase(sc_agent_vault_renewal_logins_total{datacenter=~\"$dc\"}[$__range])",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  },
  { "title": "HTTP Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(increase(sc_agent_adapters_http_requests_status{datacenter=~\"$dc\"}[$__range])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sc_agent_adapters_http_requests_status{datacenter=~\"$dc\", status_code=~\"(4|5).+\"} * 100 / sc_agent_adapters_http_requests_status{datacenter=~\"$dc\", status_code=~\"2.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "increase(sc_agent_adapters_http_tls_errors_total{datacenter=~\"$dc\"}[$__range])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}