{
 "title": "Syncthing Dirs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(syncthing_dirs_paths_timestamp_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Checks Late",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(time() - syncthing_dirs_paths_timestamp_seconds > 86400) or vector(0)",
     "legendFormat": "{{ dir }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Deleted Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (dir) (syncthing_dirs_deleted_files_total))",
     "legendFormat": "{{ dir }}"
    }
   ]
  },
  {
   "title": "Conflicting Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (dir) (syncthing_dirs_conflicts_total))",
     "legendFormat": "{{ dir }}"
    }
   ]
  },
  { "title": "Deleted Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Deleted Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "syncthing_dirs_deleted_files_total{instance=~\"$instance\"} > 0 or vector(0)",
     "legendFormat": "{{ dir }} – {{ instance }}"
    }
   ]
  },
  {
   "title": "Deleted Files Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "syncthing_dirs_deleted_files_size_bytes{instance=~\"$instance\"} > 0 or vector(0)",
     "legendFormat": "{{ dir }} – {{ instance }}"
    }
   ]
  },
  { "title": "Conflicting Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Conflicting Files Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "syncthing_dirs_conflicts_files_size_bytes{instance=~\"$instance\"} > 0 or vector(0)",
     "legendFormat": "{{ dir }} – {{ instance }}"
    }
   ]
  },
  {
   "title": "Conflicting Files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "syncthing_dirs_conflicts_total{instance=~\"$instance\"} > 0 or vector(0)",
     "legendFormat": "{{ dir }} – {{ instance }}"
    }
   ]
  }
 ]
}